<?php if ($this->pageCount): ?>
<div>
    <ul class="pagination">
        <li>
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url('member', array('controller'=>'license', 'page' => $this->previous)); ?>?company_name=<?php echo $this->company_name;?>&day=<?php echo $this->day;?>&expire=<?php echo $this->expire;?>"><<</a>
        <?php else: ?>
            <span class="disabled">
                <a href="javascript:void(0);"><<</a>
            </span>
        <?php endif; ?>
        </li>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a href="<?php echo $this->url('member', array('controller'=>'license', 'page' => $page)); ?>?company_name=<?php echo $this->company_name;?>&day=<?php echo $this->day;?>&expire=<?php echo $this->expire;?>"><?php echo $page; ?></a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a href="javascript:void(0);"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

    <?php if (isset($this->next)): ?>
        <li>
            <a href="<?php echo $this->url('member', array('controller'=>'license','page' => $this->next)); ?>?company_name=<?php echo $this->company_name;?>&day=<?php echo $this->day;?>&expire=<?php echo $this->expire;?>">>></a>
        </li>
    <?php else: ?>
        <li>
            <span class="disabled">
                <a href="javascript:void(0);">>></a>
            </span>
        </li>
    <?php endif; ?>
    </ul>
</div>
<?php endif; ?>