<h3>欢迎进入License管理系统！</h3>
<br>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong>说明：</strong> 本页面为快速导航及部分数据统计.
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
		  <!-- Default panel contents -->
		  <div class="panel-heading">数据统计</div>
		  <div class="panel-body">
		    <ul class="list-inline" style="text-align:center;">
		    	<li><p><a href="<?php echo $this->url('system',array('controller'=>'user'))?>" target="main"><?php echo $userCount;?></a></p>
		    	
		    	<p>用户数量</p></li>
		    	<li><p><?php echo $userCount;?></p><p>证书数量</p></li>
		    	<li><p><?php echo $userCount;?></p><p>公司数量</p></li>
		    	<li><p><?php echo $userCount;?></p><p>地区数量</p></li>
		    	<li><p><?php echo $userCount;?></p><p>日志数量</p></li>
		    </ul>
		  </div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default">
		  <!-- Default panel contents -->
		  <div class="panel-heading">用户</div>
		  <div class="panel-body">
		    <p>部分最近注册的用户及他们的邮箱和最后登录时间</p>
		  </div>
		
		  <!-- Table -->
		  <table class="table table-hover">
		  	<tr>
		  		<th></th>
		  		<th>用户名</th>
		  		<th>邮箱</th>
		  		<th>最后登录时间</th>
		  	</tr>
		  	<?php foreach($user as $u):?>
		    <tr>
		    	<td></td>
		    	<td><?php echo $u['username']?></td>
		    	<td><?php echo $u['email']?></td>
		    	<td><?php echo date('Y/m/d H:i:s',$u['last_login_time']);?></td>
		    </tr>
		    <?php endforeach;?>
		    <tr>
		    	<td></td>
		    	<td><a href="<?php echo $this->url('system',array('controller'=>'user'))?>" target="main">更多...</a></td>
		    </tr>
		  </table>
		</div>
	</div>
	
	<div class="col-md-6">
		<div class="panel panel-default">
		  <!-- Default panel contents -->
		  <div class="panel-heading">Panel heading</div>
		  <div class="panel-body">
		    <p>...</p>
		  </div>
		
		  <!-- Table -->
		  <table class="table">
		    <tr>
		    	<td></td>
		    </tr>
		  </table>
		</div>
	</div>
</div>