<div class="btn-group" role="group" aria-label="...">
    <a type="button" class="btn btn-info" href="<?php echo $this->url('ca', array('controller'=>'cert','action'=>'add'))?>">生成CA证书</a>
    <?php 
    if (!$this->issuerId){
    ?>
    <a type="button" class="btn btn-info" href="<?php echo $this->url('ca', array('controller'=>'cert','action'=>'addIssuer'))?>">增加颁发者</a>
    <?php 
    }else{
    ?>
        <a type="button" class="btn btn-info" href="<?php echo $this->url('ca', array('controller'=>'cert','action'=>'editIssuer','id'=>$issuerId))?>">修改颁发者</a>
    <?php 
    }
    ?>
</div>
<br>
<br>
<table class="table table-hover">
    <tr>
        <th>序号</th>
        <th>证书序列号</th>
        <th>有效期开始</th>
        <th>有效期结束</th>
        <th>有效天数</th>
        <th>公钥哈希值</th>
        <th>操作</th>
    </tr>
    <?php 
    if(count($this->paginator)):
    foreach ($this->paginator as $item):
    ?>
    <tr>
        <td><?php echo $item->id;?></td>
        <td><?php echo $this->escapehtml(strtoupper($item->serial));?></td>
        <td><?php echo $this->escapehtml($item->begin_time);?></td>
        <td><?php echo $this->escapehtml($item->end_time);?></td>
        <td><?php echo $this->escapehtml((int)$item->valid_days);?></td>
        <td><?php echo $this->escapehtml($item->sha1file);?></td>
        <td><a href="<?php echo $this->url('ca', array('controller'=>'cert', 'action'=>'certdown', 'id'=>$item->id));?>">证书下载</a></td>
    </tr>
    <?php 
    endforeach;
    endif;
    ?>
</table>

<?php echo $this->paginationcontrol($this->paginator,'Sliding','pagination.phtml');?>
