<div class="btn-group" role="group" aria-label="...">
	<a type="button" class="btn btn-info" href="<?php echo $this->url('system',array('controller'=>'userrole','action'=>'add'))?>">添加角色</a>
</div>
<br/><br/>
<?php if($paginator):?>
<table class="table table-hover">
    <tr>
        <th></th>
        <th>角色名称</th>
        <th>用户数量</th>
        <th>创建时间</th>
        <th>状态</th>
        <th>操作</th>
    </tr>
    <?php foreach ($paginator as $k=>$p) : ?>
        <tr>
        	<td><?php echo $k+1?></td>
            <td><?php echo $this->escapeHtml($p->role_name); ?></td>
           	<td><?php echo $count[$p->id];?></td>
            <td><?php if($p->createtime != 0){ echo date('Y/m/d H:i:s',$this->escapeHtml($p->createtime));}?></td>
            <td><?php if($this->escapeHtml($p->status) == 'Y'){echo '<span class="glyphicon glyphicon-ok" aria-hidden="true" style="color:green"></span>';}else{echo '<span class="glyphicon glyphicon-remove" aria-hidden="true" style="color:red"></span>';}?></td>
            <td>
                <a href="<?php echo $this->url('system',array('controller'=>'userrole','action'=>'edit','id'=>(int)$p->id))?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                <a href="javascript:void(0);" onClick="del('<?php echo $p->id;?>')"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php endif;?>
<?php
	echo $this->paginationControl(
			$this->paginator,
			'sliding',
			array('system/partial/paginator.phtml','UserRole'),
			array('route'=>'system','controller'=>'userrole')
		);
?>
<script type="text/javascript">
	function del(id){
		if(confirm('确定要删除吗？将不可恢复！')){
			window.location.href='<?php echo $this->url('system', array('controller'=>'userrole','action'=>'delete'));?>/'+id;
		}	
	}
</script>